name: Github Pull Requests Bot

on:
  pull_request:
    types: [opened]
    
jobs:
  Append-PR-Messages:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
        
    - run: go version
    - run: echo ${PR_NUMBER}
    
    - name: Move Directory
      run: cd ./tools/github-bot/

    - name: Running Github Bot
      run: go run main.go -m example.json -owner yejun614 -repo algorithm-solve -pr ${PR_NUMBER} -confirm false -sign true
